force-app/main/default/objects/InterviewEvent__c/InterviewEvent__c.object-meta.xml
<CustomObject>
    <label>Interview Event</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InterviewEventCandidate__c/InterviewEventCandidate__c.object-meta.xml
<CustomObject>
    <label>Interview Event Candidate</label>
    <nameField>
        <displayFormat>IEC-{00000}</displayFormat>
        <label>Interview Event Candidate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interview Event Candidate</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InterviewEventCandidate__c/fields/Aggregated_Score__c.field-meta.xml
<CustomField>
    <fullName>Aggregated_Score__c</fullName>
    <label>Aggregated Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InterviewEventCandidate__c/fields/Candidate_Level__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Level__c</fullName>
    <label>Candidate Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Candidate_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InterviewEventCandidate__c/fields/Candidate_Name__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Name__c</fullName>
    <formula>Candidate__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Candidate Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InterviewEventCandidate__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CandidateEventStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InterviewEventCandidate__c/fields/Ongoing_Interview__c.field-meta.xml
<CustomField>
    <fullName>Ongoing_Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ongoing Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipLabel>Ongoing Interview Event Candidates</relationshipLabel>
    <relationshipName>Ongoing_Interview_event_candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/CandidateEventStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Waiting</fullName>
        <default>true</default>
        <label>Waiting</label>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Cut</fullName>
    </customValue>
    <customValue>
        <fullName>No Show</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <masterLabel>CandidateEventStatus</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InterviewCandidatesGridHelper.cls
public with sharing class InterviewCandidatesGridHelper {
    @AuraEnabled(cacheable=true)
    public static List<InterviewEventCandidate__c> getCandidatesList(ID recordId) {
        return [Select Id,Name,Candidate_Name__c,Current_Status__c,Ongoing_Interview__r.Name,Aggregated_Score__c,Ongoing_Interview__r.Scheduled_Start_Time__c, toLabel(Candidate_Level__c) from InterviewEventCandidate__c WHERE InterviewEvent__c = :recordId];
    }
 
}