force-app/main/default/objects/Hired_Candidate__c/Hired_Candidate__c.object-meta.xml
<CustomObject>
    <label>Hired Candidate</label>
    <nameField>
        <label>Hired Candidate Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hired Candidat</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hired_Candidate__c/fields/Allocation_Status__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Status__c</fullName>
    <label>Allocation Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Allocation_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hired_Candidate__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Hired_Candidates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hired_Candidate__c/fields/Onboarding_Completed__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Onboarding Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recommendation/fields/Employee_Title__c.field-meta.xml
<CustomField>
    <fullName>Employee_Title__c</fullName>
    <label>Employee Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommendation/fields/Hired_Candidate__c.field-meta.xml
<CustomField>
    <fullName>Hired_Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hired Candidate</label>
    <referenceTo>Hired_Candidate__c</referenceTo>
    <relationshipLabel>Recommendations</relationshipLabel>
    <relationshipName>Recommendations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation/fields/Involvement_Percent__c.field-meta.xml
<CustomField>
    <fullName>Involvement_Percent__c</fullName>
    <label>Allocation Percent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recommendation/fields/Scrum_Team__c.field-meta.xml
<CustomField>
    <fullName>Scrum_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scrum Team</label>
    <referenceTo>Scrum_Team__c</referenceTo>
    <relationshipLabel>Recommendations</relationshipLabel>
    <relationshipName>Recommendations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scrum_Team__c/Scrum_Team__c.object-meta.xml
<CustomObject>
    <label>Scrum Team</label>
    <nameField>
        <label>Scrum Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scrum Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scrum_Team__c/fields/Team_Allocation_Template__c.field-meta.xml
<CustomField>
    <fullName>Team_Allocation_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team Allocation Template</label>
    <referenceTo>Scrum_Team_Template__c</referenceTo>
    <relationshipLabel>Scrum Teams</relationshipLabel>
    <relationshipName>Scrum_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Allocation_Template_Item__c/Team_Allocation_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Team Allocation Template Item</label>
    <nameField>
        <label>Team Allocation Template Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Allocation Template Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Allocation_Template_Item__c/fields/count__c.field-meta.xml
<CustomField>
    <fullName>count__c</fullName>
    <label>count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team_Allocation_Template_Item__c/fields/Involvement_Percent__c.field-meta.xml
<CustomField>
    <fullName>Involvement_Percent__c</fullName>
    <label>Involvement Percent</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Team_Allocation_Template_Item__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Candidate_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Allocation_Template_Item__c/fields/Team_Allocation_Template__c.field-meta.xml
<CustomField>
    <fullName>Team_Allocation_Template__c</fullName>
    <label>Team Allocation Template</label>
    <referenceTo>Scrum_Team_Template__c</referenceTo>
    <relationshipLabel>Team Allocation Template Items</relationshipLabel>
    <relationshipName>Team_Allocation_Template_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team_Assignment__c/Team_Assignment__c.object-meta.xml
<CustomObject>
    <label>Team Assignment</label>
    <nameField>
        <displayFormat>ASSIGNMENT-{0000}</displayFormat>
        <label>Team Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Assignment__c/fields/Hired_Candidate__c.field-meta.xml
<CustomField>
    <fullName>Hired_Candidate__c</fullName>
    <label>Hired Candidate</label>
    <referenceTo>Hired_Candidate__c</referenceTo>
    <relationshipLabel>Team Assignments</relationshipLabel>
    <relationshipName>Team_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team_Assignment__c/fields/Hired_Candidate_Level__c.field-meta.xml
<CustomField>
    <fullName>Hired_Candidate_Level__c</fullName>
    <label>Hired Candidate Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Candidate_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Assignment__c/fields/Involvement_Percent__c.field-meta.xml
<CustomField>
    <fullName>Involvement_Percent__c</fullName>
    <label>Involvement Percent</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team_Assignment__c/fields/Scrum_Team__c.field-meta.xml
<CustomField>
    <fullName>Scrum_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Scrum Team</label>
    <referenceTo>Scrum_Team__c</referenceTo>
    <relationshipLabel>Team Assignments</relationshipLabel>
    <relationshipName>Team_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Allocation_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Allocated</fullName>
        <default>true</default>
        <label>Allocated</label>
    </customValue>
    <customValue>
        <fullName>Partially Allocated</fullName>
    </customValue>
    <customValue>
        <fullName>Unallocated</fullName>
    </customValue>
    <masterLabel>Allocation Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ResourceAllocationRecoGenerator.cls
global class ResourceAllocationRecoGenerator {
    
    global class ResourceShortage{
        global String level;
        global Integer Involvement_Percent,count;
        global Team_Allocation_Template_Item__c linkedTemplateItem=null;
        ResourceShortage(String level,Integer Involvement_Percent,Integer count){
            this.level=level;
            this.Involvement_Percent=Involvement_Percent;
            this.count=count;
        }        
        ResourceShortage(String level,Integer Involvement_Percent,Integer count,Team_Allocation_Template_Item__c linkedTemplateItem){
            this.level=level;
            this.Involvement_Percent=Involvement_Percent;
            this.count=count;
            this.linkedTemplateItem=linkedTemplateItem;
        }
        
        global Override String toString(){
            return '('+this.level+'['+this.Involvement_Percent+'] ->'+this.count+')';
        }
    }
    
    global static Map<String,ResourceShortage> getShortages(ID teamId){
        
        Map<String,ResourceShortage> shortages = new Map<String,ResourceShortage>();
        
        List<Team_Allocation_Template_Item__c> expectedResources = [select tolabel(Level__c) ,Involvement_Percent__c,Count__c from Team_Allocation_Template_Item__c 
                                                                    where Team_Allocation_Template__c in (select Team_Allocation_Template__c from Scrum_Team__c where Id = :teamId)];
        
        List<Team_Assignment__c> existingResources=[SELECT tolabel(Hired_Candidate_Level__c),Involvement_Percent__c  FROM Team_Assignment__c where Scrum_Team__c=:teamId]; // group by over neither decimal nor formula working
        

         
        Map<String,Integer> existingCountByLevel= new Map<String,Integer>();
        for(Team_Assignment__c agg:existingResources){
            String key = agg.Hired_Candidate_Level__c+'|'+agg.Involvement_Percent__c;
            if(existingCountByLevel.containsKey(key)) {
                existingCountByLevel.put(key,existingCountByLevel.get(key)+1);
            }
            else 
              existingCountByLevel.put(key,1);
        }
        
        system.debug('Existing count by level:'+existingCountByLevel);

        for(Team_Allocation_Template_Item__c exp:expectedResources) {             
            String key = exp.Level__c+'|'+exp.Involvement_Percent__c;
            Integer count = (Integer)exp.Count__c;
            
            if(existingCountByLevel.containsKey(key)) {
                if(existingCountByLevel.get(key)>=exp.Count__c){
                    continue;
                }
                else 
                    count -=existingCountByLevel.get(key);
            }
            
            shortages.put(key,new ResourceShortage(exp.Level__c,exp.Involvement_Percent__c.intValue(),count,exp));               
        }
        
        system.debug('Shortages:'+shortages.values());
        return shortages;
    }
    
    @InvocableMethod(
        label='Resource Recommendation Generator'
        description='This function returns recommendations for the resources to allocate to a team.')
     global static List<List<Recommendation>> getResources(List<ResourceRecommendationGenerateRequest> inputRequests){
        List<List<Recommendation>> outputs = new List<List<Recommendation>>();
        
        for (ResourceRecommendationGenerateRequest inputRequest : inputRequests)
        {
          Map<String,ResourceShortage> shortages = getShortages(inputRequest.teamId);
            
          List<Hired_Candidate__c> availableResources=[SELECT Id,Name,Candidate__c,Allocation_Status__c,tolabel(Candidate_Level__c),Employee_Name__c FROM Hired_Candidate__c 
                                                        where Allocation_Status__c in ('Partially Allocated','Unallocated') and Onboarding_Completed__c=true ]; 
           
          Map<String,List<Hired_Candidate__c>> availableMap = new   Map<String,List<Hired_Candidate__c>>();
          for(Hired_Candidate__c hc:availableResources){
              if(hc.Allocation_Status__c=='Unallocated'){
                 if(!availableMap.containsKey(hc.Candidate_Level__c+'|100')) 
                   availableMap.put(hc.Candidate_Level__c+'|100',new List<Hired_Candidate__c>());

                availableMap.get(hc.Candidate_Level__c+'|100').add(hc);
              }
             // available for partial allocation too
            if(!availableMap.containsKey(hc.Candidate_Level__c+'|50')) 
              availableMap.put(hc.Candidate_Level__c+'|50',new List<Hired_Candidate__c>());

            availableMap.get(hc.Candidate_Level__c+'|50').add(hc);
          }
           
           system.debug('Available Resource:'+availableMap.keySet());
           List<Recommendation> recs = new List<Recommendation>(); 
           for (String key: shortages.keySet()) {

                if(availableMap.containsKey(key)){
                    ResourceShortage shortage=shortages.get(key);
                    
                    for (Hired_Candidate__c hc:availableMap.get(key)) {
                        if(shortage.count==0)
                            continue;
                        shortage.count--;
                        Recommendation rec = new Recommendation(
                            Name = hc.Employee_Name__c,
                            Description = 'Fill Shortage of '+shortage.level+' with Allocation '+shortage.Involvement_Percent+'%',
                            Hired_Candidate__c = hc.Id, 
                            Involvement_Percent__c = shortage.Involvement_Percent,
                            Employee_Title__c  = shortage.level,
                            ActionReference = 'Simple_Screen_Flow',
                            Scrum_Team__c = inputRequest.teamId,
                            AcceptanceLabel = 'Allocate',
                            RejectionLabel = 'No Thanks'
                        );
                        recs.add(rec);
                    }
                }
            }
            outputs.add(recs);
            
        }
        return outputs; 
    }
    
    global class ResourceRecommendationGenerateRequest {
        @InvocableVariable(label='Team ID')
        global String teamId;
    }
}