force-app/main/default/objects/FeedbackItem__c/fields/Interview__c.field-meta.xml
<CustomField>
    <fullName>Interview__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipLabel>Feedback Items</relationshipLabel>
    <relationshipName>Feedback_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questionaire__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FeedbackItemsController.cls
public with sharing class FeedbackItemsController {

    @AuraEnabled(cacheable=true)
    public static List<FeedbackItem__c> getFeedbackItems(String recordId) {
        return [SELECT Id, Name, Proficiency_Level__c, Comments__c FROM FeedbackItem__c WHERE Interview__c = :recordId];
    }

    @AuraEnabled
    public static string updateFeedbackItems(Object data) {
        List<FeedbackItem__c> feedbackItemsForUpdate = (List<FeedbackItem__c>) JSON.deserialize(
            JSON.serialize(data),
            List<FeedbackItem__c>.class
        );
        try {
            update feedbackItemsForUpdate;
            return 'Success: contacts updated successfully';
        }
        catch (Exception e) {
            return 'The following exception has occurred: ' + e.getMessage();
        }
    }

    @AuraEnabled
    public static void createFeedback(String questionValue, String commentValue, String feedbackNameValue, String proficiencyLevelValue, String interviewId, Integer sortOrderValue){
        try {
            System.debug(questionValue + ' ' + commentValue + ' ' + feedbackNameValue + ' ' + proficiencyLevelValue + ' ' + interviewId + ' ' + sortOrderValue);
            Questionaire__c question = new Questionaire__c();
            question.Name = questionValue;
            question.Sort_Order__c = sortOrderValue;
            insert question;

            FeedbackItem__c feedbackItem = new FeedbackItem__c();
            feedbackItem.Name = feedbackNameValue;
            feedbackItem.Proficiency_Level__c = proficiencyLevelValue;
            feedbackItem.Comments__c = commentValue;
            feedbackItem.Questionaire__c = question.Id;
            feedbackItem.Interview__c = interviewId;

            insert feedbackItem;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}