force-app/main/default/objects/EventInterviewSchedule__c/EventInterviewSchedule__c.object-meta.xml
<CustomObject>
    <label>Event Interview Schedule</label>
    <nameField>
        <label>Event Interview Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Interview Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventInterviewSchedule__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EventInterviewSchedule__c/fields/Hiring_Panel_Member__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Panel_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hiring Panel Member</label>
    <referenceTo>HiringPanelMember__c</referenceTo>
    <relationshipLabel>Event Interview Schedules</relationshipLabel>
    <relationshipName>EventInterviewSchedules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EventInterviewSchedule__c/fields/Interview__c.field-meta.xml
<CustomField>
    <fullName>Interview__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipName>EventInterviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EventInterviewSchedule__c/fields/Interview_Event__c.field-meta.xml
<CustomField>
    <fullName>Interview_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Interview Event</label>
    <referenceTo>InterviewEvent__c</referenceTo>
    <relationshipName>EventInterviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EventInterviewSchedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Interview_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventInterviewSchedule__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Hiring_Panel_Member_Availability__c/Hiring_Panel_Member_Availability__c.object-meta.xml
<CustomObject>
    <label>Hiring Panel Member Availability</label>
    <nameField>
        <displayFormat>Avail-{0000}</displayFormat>
        <label>Hiring Panel Member Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hiring Panel Members Availability</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Panel_Member_Availability__c/fields/Hiring_Panel_Member__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Panel_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hiring Panel Member</label>
    <referenceTo>HiringPanelMember__c</referenceTo>
    <relationshipLabel>Hiring Panel Members Availability</relationshipLabel>
    <relationshipName>Hiring_Panel_Members_Availability</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hiring_Panel_Member_Availability__c/fields/Interview_Event__c.field-meta.xml
<CustomField>
    <fullName>Interview_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Interview Event</label>
    <referenceTo>InterviewEvent__c</referenceTo>
    <relationshipLabel>Hiring Panel Members Availability</relationshipLabel>
    <relationshipName>Hiring_Panel_Members_Availability</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hiring_Panel_Member_Availability__c/fields/Override_role__c.field-meta.xml
<CustomField>
    <fullName>Override_role__c</fullName>
    <label>Override role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Panel_Member_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduleAnInterview.cls
public with sharing class ScheduleAnInterview {

    public static Set<Id> getAllAvailableInterviewers(DateTime availabilityCheckFrom, DateTime availabilityCheckTo, Id eventId)
    {
        List<Id> availableInterviewers = New List<Id>();
        //Get all the available interviewers for this event along with their default role.
        List<Hiring_Panel_Member_Availability__c> allAvailableMembersForThisEvent = [Select Id, Override_role__c  from Hiring_Panel_Member_Availability__c where Interview_Event__c =:eventId];
        Map<Id, String> memberRoleMap = New Map<Id, String>();
        for (Hiring_Panel_Member_Availability__c hpma : allAvailableMembersForThisEvent)
        {
            memberRoleMap.put(hpma.Hiring_Panel_Member__c, hpma.Override_role__c );
        }
        //For all of these interviewers check in EventInterviewSchedule
        List<EventInterviewSchedule__c> currentScheduleSnapshot = [Select Id, Hiring_Panel_Member__c, From__c, To__c, Interview_Event__c , Interview__c	, Status__c from EventInterviewSchedule__c 
                                                               where Hiring_Panel_Member__c  IN :memberRoleMap.keySet() and 
                                                               ( Status__c ='Scheduled' OR Status__c ='InProgress') and 
                                                               ((From__c >= :availabilityCheckFrom and From__c <= :availabilityCheckTo) OR
                                                               (To__c >= :availabilityCheckFrom and To__c <= :availabilityCheckTo))];

        // Filter the results
        // Remove the members from the map which are already part of this snapshot
		for (EventInterviewSchedule__c intwSchedule : currentScheduleSnapshot)
            memberRoleMap.remove(intwSchedule.Hiring_Panel_Member__c);
        return memberRoleMap.keySet();
    }
    
    public static void scheduleInterview(Id interviewEventCandidate, Id interviewId, List<Id> hiringPanelMembers)
    {
        
    }
    
    public static void reScheduleInterview(Id interviewEventCandidate, Id interviewId)
    {
        
    }
    
    
    public static boolean checkInterviewerAvailability(Id hiringPanelMemberId, DateTime availabilityCheckFrom, DateTime availabilityCheckTo)
     {
       //Get all the interviews which are in scheduled/inprogress state for this user on this date.
       //If there is a time conflict , then return false.
        List<EventInterviewSchedule__c> interviewerSchedule = [Select Id, From__c, To__c, Interview_Event__c , Interview__c	, Status__c from EventInterviewSchedule__c 
                                                               where Hiring_Panel_Member__c  =:hiringPanelMemberId and 
                                                               ( Status__c ='Scheduled' OR Status__c ='InProgress') and 
                                                               ((From__c >= :availabilityCheckFrom and From__c <= :availabilityCheckTo) OR
                                                               (To__c >= :availabilityCheckFrom and To__c <= :availabilityCheckTo))];
        if (interviewerSchedule == null || interviewerSchedule.isEmpty())
           return true;
    	return false;
    }
        
    

}